BEGIN;

CREATE TABLE companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(160) NOT NULL,
    tax_id VARCHAR(30) UNIQUE,
    email VARCHAR(255),
    phone VARCHAR(30),
    address VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(40) NOT NULL UNIQUE,
    description VARCHAR(255)
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    company_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,

    full_name VARCHAR(160) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    last_login_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_users_company
        FOREIGN KEY (company_id)
        REFERENCES companies(id),

    CONSTRAINT fk_users_role
        FOREIGN KEY (role_id)
        REFERENCES roles(id),

    CONSTRAINT uq_users_company_email
        UNIQUE (company_id, email)
);

CREATE TABLE employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    company_id BIGINT NOT NULL,
    user_id BIGINT UNIQUE,

    employee_code VARCHAR(40),
    full_name VARCHAR(160) NOT NULL,
    email VARCHAR(255),
    phone VARCHAR(30),

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_employees_company
        FOREIGN KEY (company_id)
        REFERENCES companies(id),

    CONSTRAINT fk_employees_user
        FOREIGN KEY (user_id)
        REFERENCES users(id),

    CONSTRAINT uq_employees_company_code
        UNIQUE (company_id, employee_code)
);


CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    company_id BIGINT NOT NULL,

    document_type VARCHAR(20),
    document_number VARCHAR(30),

    full_name VARCHAR(160) NOT NULL,

    email VARCHAR(255),
    phone VARCHAR(30),
    address VARCHAR(255),

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_customers_company
        FOREIGN KEY (company_id)
        REFERENCES companies(id),

    CONSTRAINT uq_customers_company_document
        UNIQUE (
            company_id,
            document_type,
            document_number
        )
);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    company_id BIGINT NOT NULL,

    name VARCHAR(100) NOT NULL,
    description TEXT,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_categories_company
        FOREIGN KEY (company_id)
        REFERENCES companies(id),

    CONSTRAINT uq_categories_company_name
        UNIQUE (company_id, name)
);


CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    company_id BIGINT NOT NULL,
    category_id BIGINT,

    sku VARCHAR(60) NOT NULL,
    name VARCHAR(180) NOT NULL,

    description TEXT,

    unit_price NUMERIC(12,2) NOT NULL
        CHECK (unit_price >= 0),

    cost_price NUMERIC(12,2) NOT NULL DEFAULT 0
        CHECK (cost_price >= 0),

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_products_company
        FOREIGN KEY (company_id)
        REFERENCES companies(id),

    CONSTRAINT fk_products_category
        FOREIGN KEY (category_id)
        REFERENCES categories(id)
        ON DELETE SET NULL,

    CONSTRAINT uq_products_company_sku
        UNIQUE (company_id, sku)
);

CREATE TABLE sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    company_id BIGINT NOT NULL,
    customer_id BIGINT,
    employee_id BIGINT,
    created_by BIGINT,

    sale_number VARCHAR(50) NOT NULL,

    status VARCHAR(20) NOT NULL DEFAULT 'draft'
        CHECK (
            status IN (
                'draft',
                'pending',
                'completed',
                'cancelled',
                'refunded'
            )
        ),

    currency CHAR(3) NOT NULL DEFAULT 'PEN',

    subtotal NUMERIC(12,2) NOT NULL DEFAULT 0
        CHECK (subtotal >= 0),

    discount_amount NUMERIC(12,2) NOT NULL DEFAULT 0
        CHECK (discount_amount >= 0),

    tax_amount NUMERIC(12,2) NOT NULL DEFAULT 0
        CHECK (tax_amount >= 0),

    total_amount NUMERIC(12,2) NOT NULL DEFAULT 0
        CHECK (total_amount >= 0),

    notes TEXT,

    sold_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_sales_company
        FOREIGN KEY (company_id)
        REFERENCES companies(id),

    CONSTRAINT fk_sales_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers(id)
        ON DELETE SET NULL,

    CONSTRAINT fk_sales_employee
        FOREIGN KEY (employee_id)
        REFERENCES employees(id)
        ON DELETE SET NULL,

    CONSTRAINT fk_sales_created_by
        FOREIGN KEY (created_by)
        REFERENCES users(id)
        ON DELETE SET NULL,

    CONSTRAINT uq_sales_company_number
        UNIQUE (company_id, sale_number)
);

CREATE TABLE sale_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    sale_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,

    quantity NUMERIC(12,3) NOT NULL
        CHECK (quantity > 0),

    unit_price NUMERIC(12,2) NOT NULL
        CHECK (unit_price >= 0),

    discount_amount NUMERIC(12,2) NOT NULL DEFAULT 0
        CHECK (discount_amount >= 0),

    line_total NUMERIC(12,2) NOT NULL
        CHECK (line_total >= 0),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_sale_details_sale
        FOREIGN KEY (sale_id)
        REFERENCES sales(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_sale_details_product
        FOREIGN KEY (product_id)
        REFERENCES products(id)
);

CREATE TABLE payment_methods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    company_id BIGINT NOT NULL,

    name VARCHAR(80) NOT NULL,
    code VARCHAR(40) NOT NULL,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_payment_methods_company
        FOREIGN KEY (company_id)
        REFERENCES companies(id),

    CONSTRAINT uq_payment_methods_company_name
        UNIQUE (company_id, name),

    CONSTRAINT uq_payment_methods_company_code
        UNIQUE (company_id, code)
);


CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    sale_id BIGINT NOT NULL,
    payment_method_id BIGINT NOT NULL,

    amount NUMERIC(12,2) NOT NULL
        CHECK (amount > 0),

    currency CHAR(3) NOT NULL DEFAULT 'PEN',

    status VARCHAR(20) NOT NULL DEFAULT 'pending'
        CHECK (
            status IN (
                'pending',
                'paid',
                'failed',
                'refunded'
            )
        ),

    reference VARCHAR(120),

    paid_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_payments_sale
        FOREIGN KEY (sale_id)
        REFERENCES sales(id),

    CONSTRAINT fk_payments_method
        FOREIGN KEY (payment_method_id)
        REFERENCES payment_methods(id)
);

CREATE TABLE inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    company_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,

    quantity_on_hand NUMERIC(12,3) NOT NULL DEFAULT 0
        CHECK (quantity_on_hand >= 0),

    minimum_quantity NUMERIC(12,3) NOT NULL DEFAULT 0
        CHECK (minimum_quantity >= 0),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_inventory_company
        FOREIGN KEY (company_id)
        REFERENCES companies(id),

    CONSTRAINT fk_inventory_product
        FOREIGN KEY (product_id)
        REFERENCES products(id),

    CONSTRAINT uq_inventory_company_product
        UNIQUE (company_id, product_id)
);


CREATE TABLE inventory_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    company_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    user_id BIGINT,
    sale_id BIGINT,

    movement_type VARCHAR(20) NOT NULL
        CHECK (
            movement_type IN (
                'entrada',
                'salida',
                'ajuste',
                'in',
                'out',
                'adjustment',
                'return'
            )
        ),

    quantity NUMERIC(12,3) NOT NULL
        CHECK (quantity > 0),

    reason VARCHAR(255),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_inventory_movements_company
        FOREIGN KEY (company_id)
        REFERENCES companies(id),

    CONSTRAINT fk_inventory_movements_product
        FOREIGN KEY (product_id)
        REFERENCES products(id),

    CONSTRAINT fk_inventory_movements_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE SET NULL,

    CONSTRAINT fk_inventory_movements_sale
        FOREIGN KEY (sale_id)
        REFERENCES sales(id)
        ON DELETE SET NULL
);

CREATE TABLE datasets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    company_id BIGINT NOT NULL,

    name VARCHAR(160) NOT NULL,
    source_type VARCHAR(50) NOT NULL,

    description TEXT,

    created_by BIGINT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_datasets_company
        FOREIGN KEY (company_id)
        REFERENCES companies(id),

    CONSTRAINT fk_datasets_created_by
        FOREIGN KEY (created_by)
        REFERENCES users(id)
        ON DELETE SET NULL
);

CREATE TABLE dataset_variables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    dataset_id BIGINT NOT NULL,

    name VARCHAR(120) NOT NULL,

    data_type VARCHAR(30) NOT NULL,

    variable_type VARCHAR(30),

    description TEXT,

    CONSTRAINT fk_dataset_variables_dataset
        FOREIGN KEY (dataset_id)
        REFERENCES datasets(id)
        ON DELETE CASCADE,

    CONSTRAINT uq_dataset_variables_name
        UNIQUE (dataset_id, name)
);

CREATE TABLE observations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    dataset_id BIGINT NOT NULL,
    variable_id BIGINT NOT NULL,

    numeric_value DOUBLE PRECISION,
    text_value TEXT,

    observed_at TIMESTAMPTZ,

    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_observations_dataset
        FOREIGN KEY (dataset_id)
        REFERENCES datasets(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_observations_variable
        FOREIGN KEY (variable_id)
        REFERENCES dataset_variables(id)
        ON DELETE CASCADE,

    CONSTRAINT chk_observations_value
        CHECK (
            numeric_value IS NOT NULL
            OR text_value IS NOT NULL
        )
);

CREATE TABLE statistical_analyses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    company_id BIGINT NOT NULL,
    dataset_id BIGINT,

    analysis_type VARCHAR(60) NOT NULL,

    parameters JSONB NOT NULL DEFAULT '{}'::jsonb,

    status VARCHAR(20) NOT NULL DEFAULT 'completed',

    created_by BIGINT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_statistical_analyses_company
        FOREIGN KEY (company_id)
        REFERENCES companies(id),

    CONSTRAINT fk_statistical_analyses_dataset
        FOREIGN KEY (dataset_id)
        REFERENCES datasets(id)
        ON DELETE SET NULL,

    CONSTRAINT fk_statistical_analyses_user
        FOREIGN KEY (created_by)
        REFERENCES users(id)
        ON DELETE SET NULL
);


CREATE TABLE statistical_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    analysis_id BIGINT NOT NULL,

    metric_name VARCHAR(100) NOT NULL,

    numeric_result DOUBLE PRECISION,

    result_payload JSONB NOT NULL DEFAULT '{}'::jsonb,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_statistical_results_analysis
        FOREIGN KEY (analysis_id)
        REFERENCES statistical_analyses(id)
        ON DELETE CASCADE
);

CREATE TABLE bayes_analyses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    analysis_id BIGINT NOT NULL,

    probability_a DOUBLE PRECISION NOT NULL
        CHECK (probability_a BETWEEN 0 AND 1),

    probability_b_given_a DOUBLE PRECISION NOT NULL
        CHECK (probability_b_given_a BETWEEN 0 AND 1),

    probability_b DOUBLE PRECISION NOT NULL
        CHECK (probability_b > 0 AND probability_b <= 1),

    posterior_probability DOUBLE PRECISION NOT NULL
        CHECK (posterior_probability BETWEEN 0 AND 1),

    explanation TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_bayes_analysis
        FOREIGN KEY (analysis_id)
        REFERENCES statistical_analyses(id)
        ON DELETE CASCADE
);


CREATE TABLE random_variables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    dataset_id BIGINT NOT NULL,
    variable_id BIGINT NOT NULL,

    distribution_name VARCHAR(80),

    parameters JSONB NOT NULL DEFAULT '{}'::jsonb,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_random_variables_dataset
        FOREIGN KEY (dataset_id)
        REFERENCES datasets(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_random_variables_variable
        FOREIGN KEY (variable_id)
        REFERENCES dataset_variables(id)
        ON DELETE CASCADE
);

CREATE TABLE insights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    company_id BIGINT NOT NULL,
    analysis_id BIGINT,

    title VARCHAR(180) NOT NULL,
    description TEXT NOT NULL,

    evidence JSONB NOT NULL DEFAULT '{}'::jsonb,

    severity VARCHAR(20) NOT NULL DEFAULT 'info',

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_insights_company
        FOREIGN KEY (company_id)
        REFERENCES companies(id),

    CONSTRAINT fk_insights_analysis
        FOREIGN KEY (analysis_id)
        REFERENCES statistical_analyses(id)
        ON DELETE SET NULL
);


CREATE TABLE reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    company_id BIGINT NOT NULL,

    report_type VARCHAR(60) NOT NULL,
    title VARCHAR(180) NOT NULL,

    filters JSONB NOT NULL DEFAULT '{}'::jsonb,

    file_path TEXT,

    created_by BIGINT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_reports_company
        FOREIGN KEY (company_id)
        REFERENCES companies(id),

    CONSTRAINT fk_reports_user
        FOREIGN KEY (created_by)
        REFERENCES users(id)
        ON DELETE SET NULL
);


CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    company_id BIGINT,
    user_id BIGINT,

    action VARCHAR(100) NOT NULL,

    entity_type VARCHAR(80),
    entity_id VARCHAR(80),

    ip_address INET,

    details JSONB NOT NULL DEFAULT '{}'::jsonb,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_audit_company
        FOREIGN KEY (company_id)
        REFERENCES companies(id)
        ON DELETE SET NULL,

    CONSTRAINT fk_audit_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE SET NULL
);

CREATE INDEX idx_users_company_role
ON users(company_id, role_id);

CREATE INDEX idx_customers_company_name
ON customers(company_id, full_name);

CREATE INDEX idx_products_company_name
ON products(company_id, name);

CREATE INDEX idx_products_category
ON products(category_id);

CREATE INDEX idx_sales_company_sold_at
ON sales(company_id, sold_at DESC);

CREATE INDEX idx_sales_customer
ON sales(customer_id);

CREATE INDEX idx_sale_details_sale
ON sale_details(sale_id);

CREATE INDEX idx_payments_sale_status
ON payments(sale_id, status);

CREATE INDEX idx_inventory_movements_product_date
ON inventory_movements(product_id, created_at DESC);

CREATE INDEX idx_observations_dataset_variable
ON observations(dataset_id, variable_id);

CREATE INDEX idx_statistical_analyses_company_date
ON statistical_analyses(company_id, created_at DESC);

CREATE INDEX idx_audit_logs_company_date
ON audit_logs(company_id, created_at DESC);

COMMIT;